// Website catalog. This is the single source of truth for the examples index and generated pages.

export const examples = [
  {
    id: 'metronome', title: 'Metronome', category: 'Utilities', job: 'Create', mode: 'audio', featured: true,
    description: 'Schedule a click pattern with accents, rests, tempo control, and instrument presets.',
    graph: 'Scheduled transients → Master Gain → Destination', input: 'Tempo, pattern, sound', output: 'Timed clicks',
    apis: ['AudioContext', 'AudioBufferSourceNode', 'BiquadFilterNode', 'AudioParam'], command: 'node examples/metronome.js 120 X-x-X-x-',
    seo: 'This doubles as an online metronome with sound: set the bpm, an accent pattern like X-x-X-x-, and an instrument voice, then let it click through a practice session. Run it in the browser for a quick bpm click track, or launch the same instrument from the Node CLI to drive a rehearsal, a test, or a batch render.',
  },
  {
    id: 'tuner', title: 'Tuner', category: 'Utilities', job: 'Measure', mode: 'mic',
    description: 'Estimate microphone pitch, nearest note, and tuning error in cents.',
    graph: 'Microphone → Analyser → Pitch detector', input: 'Microphone stream', output: 'Pitch, note, cents',
    apis: ['MediaStreamAudioSourceNode', 'AnalyserNode'], command: 'node examples/tuner.js 440',
    warning: 'The browser asks for microphone permission. Audio stays on this device.',
    seo: 'It works as an online instrument tuner and pitch detector: play a note into the microphone and it reports the frequency, the nearest note, and how many cents you are off. The browser demo listens live, and the Node CLI runs the identical YIN-based pitch detector against @audio/mic for tuning a guitar or any monophonic instrument from a terminal.',
  },
  {
    id: 'latency-tester', title: 'Latency tester', category: 'Utilities', job: 'Measure', mode: 'mic',
    description: 'Play short clicks through the speakers and time their return through the microphone to measure round-trip latency.',
    graph: 'Click generator → Destination; Microphone → Analyser → onset detector', input: 'Microphone stream, click interval', output: 'Round-trip latency (ms)',
    apis: ['MediaStreamAudioSourceNode', 'AnalyserNode', 'AudioBufferSourceNode'], command: 'node examples/latency-tester.js',
    warning: 'Requires speakers, not headphones, so the microphone can hear the click; keep the volume moderate. The browser asks for microphone permission.',
    seo: 'This is an audio latency test: it plays short clicks through the speakers and times how long the microphone takes to hear them back, reporting the median round-trip latency in milliseconds. Try it in the browser to check a laptop or headset audio latency, or run the Node CLI version against @audio/mic for scripted round-trip latency measurements.',
  },
  {
    id: 'level-meter', title: 'Level meter', category: 'Utilities', job: 'Measure', mode: 'mic',
    description: 'Show live microphone RMS and peak level in dBFS, uncalibrated, with fast or slow meter ballistics.',
    graph: 'Microphone → Gain → Analyser → level ballistics', input: 'Microphone stream, ballistics', output: 'RMS and peak dBFS',
    apis: ['MediaStreamAudioSourceNode', 'GainNode', 'AnalyserNode'], command: 'node examples/level-meter.js',
    warning: 'The browser asks for microphone permission. Audio stays on this device.',
    seo: 'This is a mic level meter and dB meter you can run online: it shows live RMS and peak levels in dBFS with a choice of fast or slow ballistics, though the reading is uncalibrated and not a substitute for an SPL meter. Use the browser demo to watch input levels while setting gain, or the Node CLI to print a running level meter in the terminal.',
  },

  {
    id: 'tone', title: 'Reference tone', category: 'Test signals', job: 'Create', mode: 'audio', featured: true,
    description: 'Play a reference pitch with selectable waveform and frequency.',
    graph: 'Oscillator → Gain → Destination', input: 'Waveform, frequency', output: 'Speaker audio',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/tone.js sine A4 2s',
    seo: 'This is an online tone generator: pick sine, triangle, square, or sawtooth and a frequency, and it plays a reference pitch, useful as a 440 Hz test tone or any sine wave sound you need on demand. Play it directly in the browser, or generate the same tone from the Node CLI.',
  },
  {
    id: 'sweep', title: 'Sweep', category: 'Test signals', job: 'Measure', mode: 'audio',
    description: 'Sweep across a frequency range with linear or exponential automation.',
    graph: 'Oscillator.frequency automation → Gain → Destination', input: 'Start/end frequency, duration', output: 'Speaker audio',
    apis: ['AudioContext', 'OscillatorNode', 'AudioParam'], command: 'node examples/sweep.js 20..20k exp 3s',
    warning: 'Start at low volume. High frequencies and sudden level changes can be uncomfortable.',
    seo: 'This is a frequency sweep test you can run as a speaker test from 20 Hz to 20 kHz, with linear or exponential automation across the range. Start at a low volume in the browser, or render the same sweep from the Node CLI for measurement or analysis.',
  },
  {
    id: 'noise', title: 'Noise', category: 'Test signals', job: 'Create', mode: 'audio',
    description: 'Generate white, pink, brown, blue, or violet noise.',
    graph: 'Noise source → Gain → Destination', input: 'Noise color', output: 'Speaker audio',
    apis: ['AudioContext', 'AudioBufferSourceNode', 'GainNode'], command: 'node examples/noise.js pink 2s',
    warning: 'Start at low volume; broadband noise carries energy across much of the audible spectrum.',
    seo: 'This is a noise generator: white noise, pink noise, brown noise, and the less common blue and violet colors are all available. Play it in the browser at a safe volume, or render the same seeded noise buffer from the Node CLI.',
  },
  {
    id: 'impulse', title: 'Impulse', category: 'Test signals', job: 'Measure', mode: 'audio',
    description: 'Fire a one-sample impulse for response and signal-path testing.',
    graph: 'One-sample AudioBuffer → Destination', input: 'Count, interval', output: 'Impulse clicks',
    apis: ['AudioContext', 'AudioBuffer', 'AudioBufferSourceNode'], command: 'node examples/impulse.js 5 0.5s',
    warning: 'Use low playback volume. An impulse is intentionally abrupt.',
    seo: 'This fires a one-sample impulse, useful as a click test tone for probing a signal path or measuring an impulse response. Trigger it in the browser, or render a scheduled series of impulses from the Node CLI.',
  },
  {
    id: 'dtmf', title: 'DTMF dialer', category: 'Test signals', job: 'Create', mode: 'audio',
    description: 'Synthesize telephone keypad tones from paired row and column frequencies.',
    graph: '2 Oscillators → Envelope → Destination', input: 'Digits, tone duration', output: 'DTMF audio',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/dtmf.js 5551234',
    seo: 'This is a DTMF tone generator, the touch-tone dialer sound behind telephone keypads: it synthesizes the paired row and column frequencies for any digit sequence. Dial it in the browser, or render the same DTMF audio from the Node CLI.',
  },
  {
    id: 'stereo-test', title: 'Stereo test', category: 'Test signals', job: 'Measure', mode: 'audio',
    description: 'Identify left, right, and center channels with a panned reference tone.',
    graph: 'Oscillator → StereoPanner → Envelope → Destination', input: 'Frequency, duration', output: 'Stereo audio',
    apis: ['AudioContext', 'StereoPannerNode', 'GainNode'], command: 'node examples/stereo-test.js 1k 1s',
    warning: 'Start at low volume, especially with headphones.',
    seo: 'This is a stereo channel test: a reference tone pans through left, right, and center so you can identify which speaker or headphone channel is which. Run it in the browser at a low volume, or render the same panned tone from the Node CLI.',
  },

  {
    id: 'shepard', title: 'Shepard tone', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Layer octave-spaced voices to create a pitch that appears to rise or fall forever.',
    graph: 'Octave bank → Gaussian gains → Destination', input: 'Direction, rate', output: 'Pitch illusion',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/shepard.js up 15s',
    seo: 'This is the Shepard tone illusion online: octave-spaced voices fade in and out so the pitch seems to rise or fall forever without ever settling on a top or bottom note. Play it in the browser to hear the auditory illusion, or run the Node CLI to render the same infinite tone for a demo or a test file.',
  },
  {
    id: 'risset-rhythm', title: 'Risset rhythm', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Layer tempo cycles to create a beat that appears to accelerate or decelerate forever.',
    graph: 'Scheduled click layers → Destination', input: 'Direction, center tempo', output: 'Rhythm illusion',
    apis: ['AudioContext', 'OscillatorNode', 'AudioParam'], command: 'node examples/risset-rhythm.js up 120 20s',
    seo: 'This renders the Risset rhythm illusion, the rhythmic cousin of the Shepard tone, where layered tempo cycles create a beat that seems to keep accelerating or decelerating without ever arriving. Hear it live in the browser, or render it from the Node CLI for a talk, a test signal, or further processing.',
  },
  {
    id: 'binaural-beats', title: 'Binaural beats', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Send nearby frequencies to opposite ears and hear their difference.',
    graph: '2 Oscillators → hard L/R pan → Destination', input: 'Carrier, frequency difference', output: 'Stereo audio',
    apis: ['AudioContext', 'StereoPannerNode'], command: 'node examples/binaural-beats.js 200 10 10s',
    warning: 'Headphones are required for channel isolation. Keep volume low; no health effect is claimed.',
    seo: 'This is a binaural beats generator: it sends two close frequencies to opposite ears through headphones so you hear the beat produced by their difference, with no health or cognitive effect claimed here. Run it in the browser with headphones on, or generate the same stereo signal from the Node CLI.',
  },
  {
    id: 'missing-fundamental', title: 'Missing fundamental', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Play harmonics 2–6 while omitting the pitch the listener still perceives.',
    graph: 'Harmonic oscillator bank → Gain → Destination', input: 'Implied fundamental', output: 'Harmonic complex',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/missing-fundamental.js 100 3s',
    seo: 'This demonstrates the missing fundamental illusion, also called virtual pitch: it plays only the upper harmonics of a tone and omits the fundamental, and the ear still reconstructs the implied pitch. Listen in the browser, or render the harmonic complex from the Node CLI to inspect it in an editor or an FFT.',
  },
  {
    id: 'beating', title: 'Beating', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Hear amplitude beating produced by two nearby frequencies.',
    graph: '2 nearby Oscillators → Gain → Destination', input: 'Carrier, frequency difference', output: 'Beating tone',
    apis: ['AudioContext', 'OscillatorNode'], command: 'node examples/beating.js 440 3 5s',
    seo: 'This is an acoustic beating demo: two nearby frequencies played together produce an audible beat, a slow pulsing at the rate of their difference. Try it in the browser to hear the beat frequency directly, or generate the same two-oscillator signal from the Node CLI.',
  },
  {
    id: 'octave-illusion', title: 'Octave illusion', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Swap two antiphase frequencies between ears so a single tone seems to jump register and side.',
    graph: '2 Oscillators (stepped frequency) → hard L/R pan → Destination', input: 'Low/high frequency, alternation rate', output: 'Stereo illusion',
    apis: ['AudioContext', 'OscillatorNode', 'StereoPannerNode'], command: 'node examples/octave-illusion.js 400 800 2 12s',
    warning: 'Headphones are required for channel isolation; without them the antiphase alternation collapses into one note.',
    seo: "This renders Deutsch's octave illusion: two antiphase frequencies swap between ears so a single tone seems to jump register and side, an effect that only works over headphones. Hear it in the browser, or render the stereo signal from the Node CLI to study or share it.",
  },
  {
    id: 'scale-illusion', title: 'Scale illusion', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Interleave an ascending and descending major scale between ears so listeners regroup the notes by pitch.',
    graph: 'Ascending + descending scale (stepped frequency) → hard L/R pan → Destination', input: 'Tempo, root frequency', output: 'Stereo illusion',
    apis: ['AudioContext', 'OscillatorNode', 'StereoPannerNode'], command: 'node examples/scale-illusion.js 200 261.63 8s',
    warning: 'Headphones are required; each ear must receive its own independent line for the illusion to form.',
    seo: "This renders Deutsch's scale illusion: an ascending and a descending major scale are interleaved between the ears, and most listeners regroup the notes by pitch instead of by ear, hearing two smooth contours rather than the actual jagged ones. Play it in the browser over headphones, or render the same interleaved scale from the Node CLI.",
  },
  {
    id: 'tritone-paradox', title: 'Tritone paradox', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Play sequential octave-complex tone pairs a tritone apart so up/down judgment turns ambiguous.',
    graph: 'Octave-complex bank (retuned per event) → Gaussian gains → Destination', input: 'Root pitch class, pair count/rate', output: 'Ambiguous pitch judgment',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/tritone-paradox.js 0 8 1.2',
    seo: 'This is the tritone paradox: sequential tone pairs a tritone apart are played, and whether each pair sounds like it moves up or down turns out to be ambiguous and listener-dependent. Hear it in the browser, or render the octave-complex pairs from the Node CLI for closer study.',
  },
  {
    id: 'continuity', title: 'Continuity illusion', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Punch gaps in a steady tone and fill them with louder noise bursts so the tone sounds unbroken.',
    graph: 'Oscillator (gapped Gain) + noise bursts → Destination', input: 'Frequency, gap rate, noise fill', output: 'Continuity illusion',
    apis: ['AudioContext', 'OscillatorNode', 'AudioBufferSourceNode', 'GainNode'], command: 'node examples/continuity.js 440 0.6 on 15s',
    seo: 'This demonstrates the auditory continuity illusion: gaps are punched into a steady tone and filled with louder noise bursts, and the ear perceives the tone as continuing unbroken underneath the noise. Try it in the browser, or render the gapped signal from the Node CLI to inspect exactly where the tone and the noise sit.',
  },
  {
    id: 'streaming', title: 'Auditory streaming', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Alternate two tones and let tempo and pitch distance decide whether they fuse into one stream or split into two.',
    graph: 'Oscillator (stepped frequency) → envelope → Destination', input: 'Tempo, interval (semitones)', output: 'Stream fusion or split',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/streaming.js 240 4 15s',
    seo: 'This is an auditory streaming demo, illustrating Van Noorden-style stream segregation: two alternating tones fuse into one stream or split into two depending on their tempo and pitch distance. Adjust the tempo and interval in the browser, or render the stepped-frequency signal from the Node CLI.',
  },
  {
    id: 'huggins-pitch', title: 'Huggins pitch', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Filter one ear’s copy of identical noise through a narrow phase shift so a pitch emerges that exists in neither channel.',
    graph: 'Noise → dry + cascaded Allpass → ChannelMerger → Destination', input: 'Target frequency', output: 'Binaural pitch illusion',
    apis: ['AudioContext', 'AudioBufferSourceNode', 'BiquadFilterNode', 'ChannelMergerNode'], command: 'node examples/huggins-pitch.js 600 20s',
    warning: 'Headphones are required; the pitch only emerges from the interaural phase difference, and the effect is subtle.',
    seo: 'This renders Huggins pitch, a binaural pitch illusion: identical noise is sent to both ears, but one channel is passed through a narrow phase shift, and a faint pitch emerges that exists in neither channel alone. Headphones are required; hear it in the browser, or render the same dual-channel noise from the Node CLI.',
  },
  {
    id: 'zwicker-tone', title: 'Zwicker tone', category: 'Illusions', job: 'Explore', mode: 'audio',
    description: 'Notch broadband noise, cycle it on and off, and hear a faint after-tone linger in the silence where the notch was.',
    graph: 'Noise → notch Filters → gated Gain → Destination', input: 'Notch frequency, on/off durations', output: 'Auditory afterimage',
    apis: ['AudioContext', 'AudioBufferSourceNode', 'BiquadFilterNode', 'GainNode'], command: 'node examples/zwicker-tone.js 2000 3 2 20s',
    note: 'Best heard in a quiet room; the after-tone is faint and easily masked by background noise.',
    seo: 'This renders the Zwicker tone, an auditory afterimage: broadband noise with a notch cut out of it is switched on and off, and a faint tone lingers in the silence where the notch was. It is best heard in the browser in a quiet room, or rendered from the Node CLI for closer inspection.',
  },

  {
    id: 'subtractive-synth', title: 'Subtractive synth', category: 'Synthesis', job: 'Create', mode: 'audio', featured: true,
    description: 'Shape a sawtooth oscillator with a resonant low-pass sweep and ADSR envelope.',
    graph: 'Sawtooth → BiquadFilter → ADSR Gain → Destination', input: 'Frequency, note duration', output: 'Synth note',
    apis: ['OscillatorNode', 'BiquadFilterNode', 'AudioParam'], command: 'node examples/subtractive-synth.js -d 5s',
    seo: 'This is a subtractive synthesizer you can run online: a sawtooth oscillator is shaped by a resonant low-pass filter sweep and an ADSR envelope into a single synth note. Play it in the browser, or render the same filter-sweep patch from the Node CLI.',
  },
  {
    id: 'additive', title: 'Additive synth', category: 'Synthesis', job: 'Create', mode: 'audio',
    description: 'Construct square, saw, and triangle timbres from individual harmonics.',
    graph: 'Harmonic oscillator bank → Gain → Destination', input: 'Wave, fundamental, harmonics', output: 'Synthesized waveform',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/additive.js square 220 16 3s',
    seo: 'This is an additive synthesis demo: square, saw, and triangle timbres are built up harmonic by harmonic from individual sine oscillators rather than a built-in waveform. Hear it assembled live in the browser, or render the harmonic stack from the Node CLI.',
  },
  {
    id: 'fm-synthesis', title: 'FM synth', category: 'Synthesis', job: 'Create', mode: 'audio',
    description: 'Use one oscillator to modulate another oscillator’s frequency.',
    graph: 'Modulator → Carrier.frequency → Gain → Destination', input: 'Carrier, ratio, index', output: 'FM timbre',
    apis: ['OscillatorNode', 'AudioParam', 'GainNode'], command: 'node examples/fm-synthesis.js 440 2 5 3s',
    seo: 'This is an FM synthesis example: one oscillator modulates another oscillator frequency, and the carrier-to-modulator ratio and index shape the resulting timbre from bell-like to metallic. Try it in the browser, or render the same modulator-to-carrier graph from the Node CLI.',
  },
  {
    id: 'karplus-strong', title: 'Karplus–Strong', category: 'Synthesis', job: 'Create', mode: 'audio',
    description: 'Turn a short noise burst and averaging delay into a plucked string.',
    graph: 'Noise ring buffer → feedback average → Destination', input: 'Pitch, decay', output: 'Plucked string',
    apis: ['AudioBuffer', 'AudioBufferSourceNode'], command: 'node examples/karplus-strong.js A4 4s',
    seo: 'This is a Karplus-Strong plucked string synthesis example: a short noise burst is fed into an averaging delay loop, and the feedback settles into a naturally decaying string tone. Pluck it in the browser, or render the same ring-buffer algorithm from the Node CLI.',
  },
  {
    id: 'wavetable', title: 'Wavetable synth', category: 'Synthesis', job: 'Create', mode: 'audio',
    description: 'Build custom Fourier wavetables and crossfade between two oscillators holding different timbres.',
    graph: '2 PeriodicWave Oscillators → crossfade Gain → Destination', input: 'Preset, frequency, morph amount', output: 'Custom timbre',
    apis: ['OscillatorNode', 'PeriodicWave', 'GainNode'], command: 'node examples/wavetable.js organ 220 0.3 6s',
    seo: 'This is a wavetable synthesizer online: custom Fourier-built wavetables sit behind two oscillators that crossfade between different timbres. Morph between presets in the browser, or render the same custom PeriodicWave graph from the Node CLI.',
  },
  {
    id: 'granular', title: 'Granular synth', category: 'Synthesis', job: 'Create', mode: 'audio',
    description: 'Scatter short, jittered grains from a seeded source buffer into a granular texture cloud.',
    graph: 'Source buffer → jittered grains → envelopes → Destination', input: 'Grain size, density, pitch spread', output: 'Granular texture',
    apis: ['AudioBufferSourceNode', 'AudioBuffer', 'GainNode'], command: 'node examples/granular.js 0.08 15 4 10s',
    seo: 'This is a granular synthesis demo: short, jittered grains are scattered from a seeded source buffer to build a granular texture cloud, with control over grain size, density, and pitch spread. Explore it in the browser, or render the same grain cloud from the Node CLI.',
  },

  {
    id: 'sequencer', title: 'Step sequencer', category: 'Generative', job: 'Create', mode: 'audio',
    description: 'Schedule a 16-step melody against the audio clock.',
    graph: 'Scheduled Oscillators → envelopes → Destination', input: 'Tempo, pattern', output: 'Timed sequence',
    apis: ['AudioContext', 'OscillatorNode', 'AudioParam'], command: 'node examples/sequencer.js bpm=140 -d 10s',
    seo: 'This is an online step sequencer: a 16-step melody is scheduled precisely against the audio clock rather than a JavaScript timer. Run it in the browser at any bpm, or render the same scheduled sequence from the Node CLI.',
  },
  {
    id: 'serial', title: 'Twelve-tone', category: 'Generative', job: 'Create', mode: 'audio',
    description: 'Generate pointillistic music from prime, retrograde, inverse, and retrograde-inverse rows.',
    graph: 'Row generator → scheduled voices → Destination', input: 'Tempo, duration', output: 'Generative music',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode'], command: 'node examples/serial.js 72 30s',
    seo: 'This is a twelve-tone, or serial, music generator: it derives prime, retrograde, inverse, and retrograde-inverse rows from a seeded tone row and schedules them into pointillistic music. Listen in the browser, or render the same generative row from the Node CLI.',
  },
  {
    id: 'gamelan', title: 'Gamelan', category: 'Generative', job: 'Create', mode: 'audio',
    description: 'Schedule interlocking slendro patterns with metalophone partials and gong structure.',
    graph: 'Slendro scheduler → metallic voices → Destination', input: 'Tempo, duration', output: 'Generative music',
    apis: ['AudioContext', 'OscillatorNode', 'AudioParam'], command: 'node examples/gamelan.js 120 20s',
    seo: 'This is a gamelan music generator: interlocking slendro-scale patterns, sometimes called kotekan, are scheduled with metalophone-like partials and a gong structure. Hear it in the browser, or render the same interlocking pattern from the Node CLI.',
  },
  {
    id: 'jazz', title: 'Jazz', category: 'Generative', job: 'Create', mode: 'audio',
    description: 'Generate modal harmony, walking bass, plucked improvisation, and percussion.',
    graph: 'Theory generators → instrument chains → Destination', input: 'Seeded choices', output: 'Generative performance',
    apis: ['AudioContext', 'AudioWorkletNode', 'BiquadFilterNode'], command: 'node examples/jazz.js',
    seo: 'This is a generative jazz example: modal harmony, a walking bass line, plucked improvisation, and light percussion are all generated and scheduled together into a performance that is different every run. Listen in the browser, or render the same generative ensemble from the Node CLI.',
  },
  {
    id: 'euclidean', title: 'Euclidean rhythms', category: 'Generative', job: 'Create', mode: 'audio',
    description: 'Drive 2-3 percussion voices from Bjorklund Euclidean rhythms, each with its own step and pulse count.',
    graph: 'Euclidean patterns → percussion voices → Destination', input: 'Tempo, steps, pulses per voice', output: 'Generative rhythm',
    apis: ['AudioContext', 'AudioBufferSourceNode', 'BiquadFilterNode', 'AudioParam'], command: 'node examples/euclidean.js 120 16 3,5,7 20s',
    seo: "This is a Euclidean rhythm generator built on Bjorklund's algorithm: two or three percussion voices each get their own evenly distributed step and pulse count, and the interlocking result is a generative rhythm. Try it in the browser, or render the same pattern from the Node CLI.",
  },
  {
    id: 'drone', title: 'Drone', category: 'Generative', job: 'Create', mode: 'audio',
    description: 'Play a sustained tanpura, pad, shruti, or harmonic drone voice from seeded, continuously ramped oscillator banks.',
    graph: 'Seeded voice bank (tanpura/pad/shruti/harmonic) → Master Gain → Destination', input: 'Voice, base pitch', output: 'Continuous drone',
    apis: ['AudioContext', 'OscillatorNode', 'GainNode', 'ConvolverNode'], command: 'node examples/drone.js C3 30s',
    seo: 'This plays a tanpura drone in the browser: choose the tanpura, pad, shruti, or harmonic voice for a sustained meditation drone tone built from seeded, slowly drifting oscillator banks with no steps or clicks. The Node CLI renders the same drone for practice, backing a raga, or looping in the background while you work.',
  },

  {
    id: 'speaker', title: 'Speaker hello world', category: 'API', job: 'Create', mode: 'audio',
    description: 'Play the smallest useful realtime graph through the system output.',
    graph: 'Oscillator → Gain → Destination', input: 'Duration', output: 'System speakers',
    apis: ['AudioContext', 'AudioDestinationNode'], command: 'node examples/speaker.js',
    seo: 'This is the minimal hello-world example for the Web Audio API in Node: an oscillator into a gain into the destination, playing through the system speakers with no browser involved. It is the smallest AudioContext example in this collection, and the same few lines also run unmodified in the browser.',
  },
  {
    id: 'lfo', title: 'LFO tremolo', category: 'API', job: 'Create', mode: 'audio',
    description: 'Connect an oscillator to an AudioParam and modulate gain at audio-clock precision.',
    graph: 'LFO + ConstantSource → Gain.gain ← Carrier', input: 'Rate, depth, waveform', output: 'Tremolo tone',
    apis: ['ConstantSourceNode', 'OscillatorNode', 'AudioParam'], command: 'node examples/lfo.js rate=5 depth=0.5 -d 10s',
    seo: 'This is an LFO tremolo effect: a low frequency oscillator modulates a carrier gain at audio-clock precision, with adjustable rate, depth, and LFO waveform. Hear the tremolo in the browser, or render the same modulation graph from the Node CLI.',
  },
  {
    id: 'spatial', title: 'Spatial panning', category: 'API', job: 'Create', mode: 'audio',
    description: 'Move a source from left to right through three-dimensional space.',
    graph: 'Oscillator → Panner → Gain → Destination', input: 'Position curve, duration', output: 'Spatialized audio',
    apis: ['PannerNode', 'AudioListener', 'AudioParam'], command: 'node examples/spatial.js -d 5s',
    seo: 'This is a 3D spatial audio panning example built on PannerNode and AudioListener: a source moves through three-dimensional space from left to right. Try it in the browser, or render the same spatialized graph from the Node CLI.',
  },
  {
    id: 'worklet', title: 'AudioWorklet', category: 'API', job: 'Create', mode: 'worklet',
    description: 'Register a custom processor, expose a parameter, and render its output.',
    graph: 'AudioWorkletProcessor → AudioWorkletNode → Destination', input: 'Processor code, AudioParam', output: 'Custom DSP audio',
    apis: ['AudioWorklet', 'AudioWorkletNode', 'AudioWorkletProcessor'], command: 'node examples/worklet.js',
    note: 'The browser adapter registers a Blob URL. WAA also supports inline callback registration in Node.',
    seo: 'This is an AudioWorklet example: it registers a custom AudioWorkletProcessor, exposes an AudioParam, and renders the output of that processor. Run it in the browser, where the adapter registers a Blob URL for the processor, or from the Node CLI, which also supports inline callback registration.',
  },
  {
    id: 'linked-params', title: 'Linked AudioParams', category: 'API', job: 'Measure', mode: 'offline',
    description: 'Drive multiple gain parameters from one ConstantSourceNode.',
    graph: 'ConstantSource → 2 Gain AudioParams → mix → AudioBuffer', input: 'Shared automation curve', output: 'Offline AudioBuffer',
    apis: ['OfflineAudioContext', 'ConstantSourceNode', 'AudioParam'], command: 'node examples/linked-params.js',
    seo: 'This shows a shared AudioParam automation graph: one ConstantSourceNode drives two separate gain parameters from the same automation curve, rendered offline to an AudioBuffer. Run it from the Node CLI, or open it in the browser to see the same offline render.',
  },
  {
    id: 'fft', title: 'FFT spectrum', category: 'API', job: 'Measure', mode: 'offline', featured: true,
    description: 'Render a two-tone signal and inspect its frequency-domain peaks.',
    graph: '2 Oscillators → Analyser → AudioBuffer', input: 'Signal, FFT size', output: 'Spectrum bins, peaks',
    apis: ['OfflineAudioContext', 'AnalyserNode'], command: 'node examples/fft.js',
    seo: 'This is an FFT spectrum analyzer example: a two-tone signal is rendered offline and inspected with an AnalyserNode to find its frequency-domain peaks. Run it from the Node CLI, or open it in the browser to render and inspect the same spectrum.',
  },
  {
    id: 'render-to-buffer', title: 'Offline render', category: 'API', job: 'Process', mode: 'offline', featured: true,
    description: 'Render a complete graph to an AudioBuffer with no speakers or audio device.',
    graph: 'Offline graph → AudioDestination → AudioBuffer', input: 'Graph, length, sample rate', output: 'AudioBuffer',
    apis: ['OfflineAudioContext', 'AudioBuffer'], command: 'node examples/render-to-buffer.js',
    seo: 'This is a minimal OfflineAudioContext example: a complete graph renders straight to an AudioBuffer with no speakers, no audio device, and no browser required. Run it from the Node CLI for a batch render, or open it in the browser to see the identical offline graph.',
  },
  {
    id: 'process-file', title: 'Process a file', category: 'API', job: 'Process', mode: 'file', featured: true,
    description: 'Decode an audio file, apply EQ and compression, then render the processed result.',
    graph: 'File → decode → high-shelf EQ → compressor → AudioBuffer', input: 'Audio file', output: 'Processed AudioBuffer',
    apis: ['decodeAudioData', 'BiquadFilterNode', 'DynamicsCompressorNode'], command: 'node examples/process-file.js input.mp3',
    note: 'The browser preview accepts formats the browser can decode. In Node, WAA uses @audio/decode for broader, runtime-independent codec coverage.',
    seo: 'This decodes an audio file and processes it entirely offline: a high-shelf EQ followed by a compressor, then rendered to a finished AudioBuffer. Drop a file into the browser preview, or run the Node CLI with @audio/decode for broader, runtime-independent codec coverage.',
  },
  {
    id: 'pipe-stdout', title: 'Pipe PCM to stdout', category: 'API', job: 'Process', mode: 'node', featured: true,
    description: 'Send raw PCM from an AudioContext to any Node writable stream.',
    graph: 'Audio graph → sinkId Writable → aplay/ffmpeg/sox', input: 'Audio graph', output: '16-bit interleaved PCM',
    apis: ['AudioContext', 'AudioDestinationNode', 'WritableStream'], command: 'node examples/pipe-stdout.js | ffplay -f s16le -ar 44100 -ac 2 -',
    seo: 'This streams raw PCM audio straight from an AudioContext to any Node writable stream, so it can be piped to aplay, sox, or ffplay from the command line. It is a Node-only adapter with no browser equivalent, since a browser page has no process.stdout to pipe into.',
  },
  {
    id: 'mic', title: 'Mic level', category: 'API', job: 'Capture', mode: 'mic', featured: true,
    description: 'Route a live microphone through a gain and analyser with an RMS meter.',
    graph: 'Microphone → Gain → Analyser → Destination', input: 'Microphone stream', output: 'Monitored audio, RMS',
    apis: ['MediaStreamAudioSourceNode', 'GainNode', 'AnalyserNode'], command: 'node examples/mic.js gain=0.8',
    warning: 'Use headphones to avoid acoustic feedback. The browser asks for microphone permission.',
    note: 'The browser preview keeps monitoring muted to prevent feedback. The Node CLI can route the graph to speakers.',
    seo: 'This is a live microphone level meter: it routes the mic through a gain and an AnalyserNode with an RMS meter, letting you check input levels and set gain before recording. Run it in the browser, where monitoring stays muted to prevent feedback, or from the Node CLI, which can route the graph to speakers.',
  },
  {
    id: 'recorder', title: 'Recorder', category: 'API', job: 'Capture', mode: 'mic',
    description: 'Capture microphone audio with a live level meter and save a recording.',
    graph: 'Microphone → Gain → recorder → file', input: 'Microphone stream', output: 'Recorded audio file',
    apis: ['MediaStreamAudioSourceNode', 'ScriptProcessorNode'], command: 'node examples/recorder.js take1 gain=2',
    warning: 'Use headphones to avoid feedback. The browser asks for microphone permission.',
    note: 'The browser adapter saves the MediaRecorder format it supports. The Node CLI writes PCM WAV.',
    seo: 'This is a browser audio recorder with a live level meter: it captures microphone audio and saves it, using MediaRecorder in the browser and PCM WAV from the Node CLI. Use headphones to avoid feedback while recording either way.',
  },
  {
    id: 'reverb', title: 'Convolver reverb', category: 'API', job: 'Process', mode: 'audio',
    description: 'Convolve a plucked string through a seeded exponential-decay impulse response and blend dry with wet.',
    graph: 'Plucked buffer → dry Gain + Convolver → wet Gain → Destination', input: 'Decay time, wet amount', output: 'Reverberated audio',
    apis: ['ConvolverNode', 'AudioBuffer', 'GainNode'], command: 'node examples/reverb.js 2 0.35 3s',
    seo: 'This is a convolution reverb example: a plucked string is convolved through a seeded exponential-decay impulse response and blended with the dry signal. Adjust decay time and wet amount in the browser, or render the same convolver graph from the Node CLI.',
  },
]

export const byId = new Map(examples.map(example => [example.id, example]))
export const categories = [...new Set(examples.map(example => example.category))]
export const jobs = [...new Set(examples.map(example => example.job))]
export const featured = examples.filter(example => example.featured)
