import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'

const root = fileURLToPath(new URL('..', import.meta.url))
await build({
  absWorkingDir: root,
  entryPoints: ['assets/render-worker.js'],
  outfile: 'assets/render-worker.bundle.js',
  bundle: true,
  platform: 'browser',
  format: 'esm',
  minify: true,
  keepNames: true,
  banner: { js: '// Generated by scripts/build-browser.mjs from the package DSP and hero.js. Do not edit.' },
  plugins: [{
    name: 'offline-preview',
    setup(build) {
      build.onResolve({ filter: /^web-audio-api$/ }, () => ({ path: resolve(root, 'assets/hero-offline-context.js') }))
      // The previews generate samples or receive decoded PCM. Ship no codec payloads.
      build.onResolve({ filter: /^@audio\/decode$/ }, () => ({ path: 'decode', namespace: 'preview' }))
      build.onLoad({ filter: /.*/, namespace: 'preview' }, () => ({
        contents: 'export default function () { throw new Error("Decode files before sending them to the preview renderer") }',
      }))
    },
  }],
})
